server:
  port: 8080

spring:
  application:
    name: nebula-user

  datasource:
    url: JDBC:mysql://localhost:3306/nebula_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-flex:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    print-banner: false

